---
- name: "Configuring HTTPD "
  hosts: localhost
  tasks:
    - name: "INSTALLING HTTPD"
      yum:
        name: httpd
        state: latest

    - name: "CREATING CONFIGURATION FILE"
      file:
        path: /etc/httpd/conf.d/new.conf
        state: touch

      file:
        path: /var/www/html/index.html
        state: touch

    - name: "CREATING INDEX.HTML"
      lineinfile:
        path: /var/www/html/index.html
        line: <h1>SherLOCKED</h1>

    - name: "CONF FILE" 
      blockinfile:
        path: /etc/httpd/conf.d/new.conf
        create: yes
        block: |
          <VirtualHost *:80>
            ServerName      www.bakerstreet.com
            DocumentRoot    /var/www/html
          </VirtualHost>

    - name: "RESTARTING AND ENABLING SERVICES"
      service:
        name: httpd
        state: restarted
        enabled: yes
          
    - firewalld:
        service: http
        permanent: yes
        state: enabled
        
    - name: "ENTRIES MADE IN /ETC/HOSTS FILE"
      lineinfile:
        path: /etc/hosts
        insertbefore: '^192'
        line: '10.76.1.101      www.bakerstreet.com'

        
    - name: "COMPILLING OUTPUT.."
      command: firefox http://www.bakerstreet.com
                        
